title: "Aditya Sapre"
email: aas5969@psu.edu
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "http://adityasapre001.github.io/" 
github_username: adityasapre001
sass:
  sass_dir: _sass

icon: /assets/img/logoimage.jpg
